In [22]:
import random

import numpy as np

# Часть 1

## 1. Написать функцию формирования порождающей и проверочной матриц расширенного кода Голея (24,12,8).

In [23]:
B = [[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
     [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
     [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
     [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
     [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
     [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
     [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
     [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
     [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
     [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
     [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]]

In [24]:
def G_Golay():
    G = np.zeros((12, 24), dtype=int)
    G[:, :12] = np.eye(12, dtype=int)
    for i in range(12):
        G[i][12:] = B[i]
    return G.astype(int)


G_matrix = G_Golay()
G_matrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
        0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
        1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
        1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
        0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
        0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
        1, 1],
       [0, 0, 0, 0, 0

In [25]:
def H_Golay(G):
    n = len(G.T)
    k = len(G)
    n_k = n - k
    H = np.zeros((n, n_k), dtype=int)
    I = np.eye(n_k, dtype=int)
    H[:k, :] = I
    H[k:, :] = G[:, k:]
    return H


H_matrix = H_Golay(G_matrix)
H_matrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
       [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
       [0,

## 2. Провести исследование расширенного кода Голея для одно-, двух-, трёх- и четырёхкратных ошибок.

In [26]:
def get_error(receive, H, B):
    s = receive @ H % 2
    u1 = None
    if sum(s) <= 3:
        u1 = np.array(s)
        u1 = np.hstack((u1, np.zeros(len(s), dtype=int)))
    else:
        for i in range(len(B)):
            temp = (s + B[i]) % 2
            if sum(temp) <= 2:
                ei = np.zeros(len(s), dtype=int)
                ei[i] = 1
                u1 = np.hstack((temp, ei))
    if u1 is not None:
        u1
    else:
        sB = s @ B % 2
        if sum(sB) <= 3:
            u1 = np.hstack((np.zeros(len(s), dtype=int), sB))
        else:
            for i in range(len(B)):
                temp = (sB + B[i]) % 2
                if sum(temp) <= 2:
                    ei = np.zeros(len(s), dtype=int)
                    ei[i] = 1
                    u1 = np.hstack((ei, temp))
    return u1


def set_error(send, error_count, G, H, B):
    print(f'Исходное сообщение: {send}')

    receive = send @ G % 2
    print(f'Отправленное сообщение {receive}')

    error = np.zeros(receive.shape[0], dtype=int)
    error_indices = random.sample(range(receive.shape[0]), error_count)
    for index in error_indices:
        error[index] = 1
    print(f'Ошибка: {error}')

    receive = (receive + error) % 2
    print(f'Сообщение с ошибкой {receive}')

    error = get_error(receive, H, B)
    if error is None:
        print('Ошибка обнаружена, нельзя исправить')
        return

    message = (receive + error) % 2
    print(f'Исправленное отправленное сообщение: {message}')

    receive = send @ G % 2
    if not np.array_equal(receive, message):
        print('Сообщение было декодировано с ошибкой')

### Однократная ошибка

In [27]:
send = np.array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0])
set_error(send, 1, G_matrix, H_matrix, B)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Ошибка: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
Сообщение с ошибкой [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 1 1]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


### Двукратная ошибка

In [28]:
set_error(send, 2, G_matrix, H_matrix, B)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Ошибка: [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 0 1]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


### Трехкратная ошибка

In [29]:
set_error(send, 3, G_matrix, H_matrix, B)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Ошибка: [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
Сообщение с ошибкой [1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 1 1]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


### Четырёхкратная ошибка

In [30]:
set_error(send, 4, G_matrix, H_matrix, B)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Ошибка: [0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 0 1 1 1 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 0 1]
Ошибка обнаружена, нельзя исправить


# Часть 2

## 1. Написать функцию формирования порождающей и проверочных матриц кода Рида-Маллера 𝑅𝑀(𝑟,𝑚) на основе параметров 𝑟 и 𝑚.

In [31]:
def reed_muller_matrix(r, m):
    if r == 0:
        return np.ones((1, 2 ** m), dtype=int)

    if r == m:
        G_m = reed_muller_matrix(m - 1, m)
        bottom_row = np.zeros((1, 2 ** m), dtype=int)
        bottom_row[0, -1] = 1
        return np.vstack([G_m, bottom_row])

    G_r_m = reed_muller_matrix(r, m - 1)
    G_r_m_1 = reed_muller_matrix(r - 1, m - 1)

    top = np.hstack([G_r_m, G_r_m])
    bottom = np.hstack([np.zeros((G_r_m_1.shape[0], G_r_m_1.shape[1]), dtype=int), G_r_m_1])

    return np.vstack([top, bottom])

## 2. Провести исследование кода Рида-Маллера 𝑅𝑀(1,3) для одно- и двукратных ошибок.

In [32]:
G = reed_muller_matrix(1, 3)
G

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]])

In [33]:
def kronecker(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    result = np.zeros((rows_A * rows_B, cols_A * cols_B), dtype=A.dtype)
    for i in range(rows_A):
        for j in range(cols_A):
            result[i * rows_B:(i + 1) * rows_B, j * cols_B:(j + 1) * cols_B] = A[i, j] * B
    return result

In [34]:
def Hmi_matrix(H, m, i):
    matrix = np.eye(2 ** (m - i), dtype=int)
    matrix = kronecker(matrix, H)
    matrix = kronecker(matrix, np.eye(2 ** (i - 1)))
    return matrix

In [35]:
def set_error_RM(send, errors_count, G, m):
    print(f'Исходное сообщение: {send}')
    
    receive = send @ G % 2
    print(f'Отправленное сообщение: {receive}')
    
    error = np.zeros(receive.shape[0], dtype=int)
    error_indices = random.sample(range(receive.shape[0]), errors_count)
    for index in error_indices:
        error[index] = 1
    print(f'Допущенная ошибка: {error}')
    
    receive = (receive + error) % 2
    print(f'Сообщение с ошибкой: {receive}')

    for i in range(len(receive)):
        if receive[i] == 0:
            receive[i] = -1
            
    w_array = []
    H = np.array([[1, 1], [1, -1]])
    w_array.append(receive @ Hmi_matrix(H, m, 1))
    for i in range(2, m + 1):
        w_array.append(w_array[-1] @ Hmi_matrix(H, m, i))
        
    maximum = w_array[0][0]
    index = -1
    for i in range(len(w_array)):
        for j in range(len(w_array[i])):
            if abs(w_array[i][j]) > abs(maximum):
                index = j
                maximum = w_array[i][j]
                
    counter = 0
    for i in range(len(w_array)):
        for j in range(len(w_array[i])):
            if abs(w_array[i][j]) == abs(maximum):
                counter += 1
            if counter > 1:
                print('Невозможно исправить ошибку')
                return
            
    message = list(map(int, list(('{' + f'0:0{m}b' + '}').format(index))))
    message.append(1 if maximum > 0 else 0)
    print(f'Исправленное сообщение: {np.array(message[::-1])}')
    
    if not np.array_equal(send, message):
        print('Сообщение было декодировано с ошибкой')

### Однократная ошибка

In [36]:
m = 3
send = np.array([1, 0, 0, 1])
set_error_RM(send, 1, G, m)

Исходное сообщение: [1 0 0 1]
Отправленное сообщение: [1 1 1 1 0 0 0 0]
Допущенная ошибка: [0 0 0 1 0 0 0 0]
Сообщение с ошибкой: [1 1 1 0 0 0 0 0]
Исправленное сообщение: [1 0 0 1]


### Двукратная ошибка

In [37]:
set_error_RM(send, 2, G, m)

Исходное сообщение: [1 0 0 1]
Отправленное сообщение: [1 1 1 1 0 0 0 0]
Допущенная ошибка: [0 1 0 0 0 0 1 0]
Сообщение с ошибкой: [1 0 1 1 0 0 1 0]
Невозможно исправить ошибку


# 3. Провести исследование кода Рида-Маллера 𝑅𝑀(1,4) для одно-, двух-, трёх- и четырёхкратных ошибок.

In [38]:
G = reed_muller_matrix(1, 4)
G

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

### Однократная ошибка

In [39]:
m = 4
send = np.array([1, 0, 1, 0, 1])
set_error_RM(send, 1, G, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение: [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
Сообщение с ошибкой: [1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


### Двукратная ошибка

In [41]:
set_error_RM(send, 2, G, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение: [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
Сообщение с ошибкой: [1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


### Трёхкратная ошибка

In [42]:
set_error_RM(send, 3, G, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение: [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0]
Сообщение с ошибкой: [1 1 0 0 1 0 1 0 0 1 1 1 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


### Четырёхкратная ошибка

In [43]:
set_error_RM(send, 4, G, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение: [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1]
Сообщение с ошибкой: [0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 0]
Невозможно исправить ошибку
